server:
  port: 8000
  servlet:
    context-path: /

spring:
  application:
    name: education-platform-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:education_platform_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Seoul
  h2:
    console:
      enabled: true
      path: /h2-console
  jwt:
    secret: ${JWT_SECRET:skcc-aihack25-team23-2hong-dev-secret-key}
    access-token-expiration: 3600000  # 1시간
    refresh-token-expiration: 604800000  # 7일
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 